## Matriks
* Penulisan matriks orde $m\times n$
  * $m \rightarrow$ baris (indeks: $i$)
  * $n \rightarrow$ kolom (indeks: $j$)

$$
{\bf A} = \left[
\begin{matrix}
a_{11} & a_{12} & a_{13}  & ... & a_{1n} \\
a_{21} & a_{22} & a_{23}  & ... & a_{2n} \\
a_{31} & a_{32} & a_{33}  & ... & a_{3n} \\
\vdots&\vdots&\vdots&\vdots&\vdots\\
a_{m1} & a_{m2} & a_{m3}  & ... & a_{mn}
\end{matrix}
\right]
$$

* Contoh matriks $2\times 3$ $\rightarrow$ 2 baris, 3 kolom
$$
{\bf A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6 
\end{bmatrix}
$$

Deklarasi matriks dalam Python list:

In [1]:
a=[[1, 2, 3],[4, 5, 6]]

print(a)

[[1, 2, 3], [4, 5, 6]]


In [19]:
# menggunakan numpy
import numpy as np

print("inisialisasi langsung")
ma = np.array([[1, 2, 3], 
               [4, 5, 6]])

print('matriks a:')
print(ma)

print()

print("melalui list yang pernah dideklarasikan")
a=[[1,2,4],
   [3,5,7],
   [5,6,1]]
mb = np.array(a)
print('matriks b:')
print(mb)

print()

print("menggunakan pustaka yang tersedia:")
mr=np.random.rand(5,)
print(mr)

inisialisasi langsung
matriks a:
[[1 2 3]
 [4 5 6]]

melalui list yang pernah dideklarasikan
matriks b:
[[1 2 4]
 [3 5 7]
 [5 6 1]]

menggunakan pustaka yang tersedia:
[[0.99327072 0.27354284 0.67350499 0.4889382 ]
 [0.42445589 0.09455275 0.58745536 0.87475522]
 [0.28190733 0.95686917 0.08537138 0.82613471]
 [0.19700029 0.82287537 0.91213084 0.51335273]
 [0.54159668 0.03929526 0.77365648 0.69874383]]


# Jenis-jenis matriks

1. Matriks nol: \
   matriks yang elemennya bernilai nol.
3. matriks identitas ${\bf I} = {\bf 1}$ \
   Matriks yang ekivalen dengan matriks bernilai 1. dengan demikian, \
   $${\bf A} \cdot {\bf 1} = {\bf 1} \cdot {\bf A} = {\bf A}$$
5. matriks baris \
   vector satu baris, contoh \
   $${\bf V} = \left[\begin{matrix} 0.1 & 0.2 & 3.0 & 4.5\end{matrix}\right]$$
7. matriks kolom \
   vector satu kolom, contoh \
   $$
   {\bf V} = \left[
   \begin{matrix} 0.1\\ 0.2\\ 3.0\\ 4.5 \end{matrix}
   \right]
   $$ 
   Untuk menghemat tempat, dapat pula ditulis
   ${\bf V} = \left\{\begin{matrix}0.1 & 0.2 & 3.0 & 4.5\end{matrix}\right\}$
9. matriks persegi \
   Matriks dengan m=n
11. matriks diagonal \
    Matriks dengan elemen bernilai nol kecuali di diagonal, contoh
    $$
    {\bf A} = \left[
    \begin{matrix}
    1 &0 &0 \\
    0 &12 &0 \\
    0 &0 &6
    \end{matrix}
    \right]
    $$
13. matriks segitiga atas (upper), ${\bf U}$, contoh\
    $$
    {\bf U} = \left[
    \begin{matrix}
    2 &3 &2 \\
    0 &3 &7 \\
    0 &0 &5
    \end{matrix}
    \right]
    $$
15. matriks segitiga bawah, (lower), ${\bf L}$, contoh
    $$
    {\bf L} = \left[
    \begin{matrix}
    2 &0 &0 \\
    2 &3 &0 \\
    7 &3 &5
    \end{matrix}
    \right]
    $$    

## Operasi-operasi matriks

* Transpose matriks

Matriks dengan penunjuk kolom dan baris ditukar.

$$
\begin{aligned}
{\bf B} &= {\bf A}^T \\
b_{ij} &= a_{ji}
\end{aligned}
$$

* Trace matriks

Trace matriks didefinisikan sebagai jumlah dari elemen-elemen diagonalnya. Besaran ini didefinisikan hanya pada matriks persegi, dengan $m=n$.

$$
\text{tr}({\bf A}) = \sum_{i}^n a_{ii}
$$

* Norm matriks (_Frabenius Norm_, _Eucledian Norm_)

Norm didefinisikan sebagai besaran jarak dari matriks.

$$
|| {\bf A} || = \sqrt{\sum_i^m \sum_j^n a_{ij}^2}
$$


In [104]:
A=100*np.random.rand(5,5)
A=A.astype(int)
B=np.transpose(A)

print("Matriks asal")
print(A)
print()
print("Matriks transpos")
print(B)

trA=np.trace(A)
trB=np.trace(B)

print()
print(f'trace matriks A={trA}; trace matriks B={trB}')

print(np.linalg.norm(A))

Matriks asal
[[48 72 89 82  0]
 [ 0 53 38 66 36]
 [ 2 98 78 44 91]
 [12 80 47 72 74]
 [ 1 31  1 66 26]]

Matriks transpos
[[48  0  2 12  1]
 [72 53 98 80 31]
 [89 38 78 47  1]
 [82 66 44 72 66]
 [ 0 36 91 74 26]]

trace matriks A=277; trace matriks B=277
288.7126599233224


Untuk mengetahui bentuk atau orde matriks dapat digunakan properti ``shape`` dari sebuah matriks.\
baris: ``m=shape[0]`` dan kolom: ``n=shape[1]``

In [103]:
# Menggunakan fungsi operasi matriks sendiri

def gfTranspose(A):
    B=np.zeros(A.shape)
    m=A.shape[0]
    n=A.shape[1]
    for i in range(n):
        for j in range(m):
            B[i,j] = A[j,i]
    return B

def gfTrace(A):
    tr=0.0;
    n=A.shape[0]
    for i in range(n):
        tr+=A[i,i]
    return tr

def gfNorm(A):
    nn=0;
    m=A.shape[0]
    n=A.shape[1]
    for i in range(m):
        for j in range(n):
            nn+=A[i,j]*A[i,j]
    return np.sqrt(nn)

C=gfTranspose(A)
tr=gfTrace(A)
nn=gfNorm(A)

print(f'transpose matriks C:\n{C}')
print()
print(f'trace matriks A: {tr}')
print(f'norm matriks A: {nn}')

transpose matriks C:
[[83.  2. 66. 20. 31.]
 [14. 84. 32. 37.  7.]
 [81. 49. 87. 46. 75.]
 [51. 20. 69. 64. 28.]
 [35. 82. 64. 69. 87.]]

trace matriks A: 405.0
norm matriks A: 289.12454063949673


### Penjumlahan-pengurangan

$$
{\bf A} + {\bf B} = \left[ 
\begin{matrix}
(a_{11}+b_{11}) & (a_{12}+b_{12}) & ... & (a_{1n}+b_{1n}) \\
(a_{21}+b_{21}) & (a_{22}+b_{22}) & ... & (a_{2n}+b_{2n}) \\
(a_{31}+b_{31}) & (a_{32}+b_{32}) & ... & (a_{3n}+b_{3n}) \\
\vdots&\vdots&\vdots&\vdots \\
(a_{m1}+b_{m1}) & (a_{m2}+b_{m2}) & ... & (a_{mn}+b_{mn})
\end{matrix}
\right]
$$

Untuk setiap elemen:

$$
\begin{aligned}
{\bf C} &=& {\bf A} + {\bf B} \\
&& \\
c_{ij} &=& a_{ij}+b_{ij}
\end{aligned}
$$

* Pengurangan matriks

Pengurangan matriks dapat dipandang sebagai penjumlahan dengan negasi matriks,

$$
{\bf A} - {\bf B} = {\bf A} + (-{\bf B})
$$


dengan,
$$
-{\bf B} = \left[
\begin{matrix}
-b_{11} & -b_{12} & -b_{13}  & ... & -b_{1n} \\
-b_{21} & -b_{22} & -b_{23}  & ... & -b_{2n} \\
-b_{31} & -b_{32} & -b_{33}  & ... & -b_{3n} \\
\vdots&\vdots&\vdots&\vdots&\vdots\\
-b_{m1} & -b_{m2} & -b_{m3}  & ... & -b_{mn}
\end{matrix}
\right]
$$

In [54]:
A=np.array([[1,2],[3,4]])
B=np.array([[0.5, 0.4], [1.5, 3.0]])

print(f'Hasil penjumlahan:\n {A+B}')
print(f'Hasil pengurangan:\n {A-B}')

Hasil penjumlahan:
 [[1.5 2.4]
 [4.5 7. ]]
Hasil pengurangan:
 [[0.5 1.6]
 [1.5 1. ]]



### Perkalian matriks

* Operasi dengan skalar: operasi dilakukan ke setiap elemen
$$
k \times {\bf A} = \left[
\begin{matrix}
k\times a_{11} & k\times a_{12} & k\times a_{13}  & ... & k\times a_{1n} \\
k\times a_{21} & k\times a_{22} & k\times a_{23}  & ... & k\times a_{2n} \\
k\times a_{31} & k\times a_{32} & k\times a_{33}  & ... & k\times a_{3n} \\
\vdots&\vdots&\vdots&\vdots&\vdots\\
k\times a_{m1} & k\times a_{m2} & k\times a_{m3}  & ... & k\times a_{mn}
\end{matrix}
\right]
$$

* Perkalian elemen

$$
\begin{aligned}
{\bf C} &={\bf A} \odot {\bf B} \\
c_{ij} &=a_{ij}b_{ij}
\end{aligned}
$$

* Dot product (Inner product)

$$
\begin{aligned}
{\bf A}\cdot{\bf B} &= {\bf C} \\
c_{ij} &= \sum_{i,j} a_{ij} b_{ji}
\end{aligned}
$$

Dalam Python inner product tidak sma dengan dot product, didefinisikan sebagai,

$$
{\bf A}\cdot {\bf B} = \text{inner}({\bf A}, {\bf B}^T)
$$

Jumlah kolom matriks $\bf A$ harus sama dengan jumlah baris matriks ${\bf B}$. Notasi jumlah (_sum_) untuk dua indeks dapat secara singkat ditulis seperti di atas, dengan,

$$
\sum_{i,j} \cong \sum_i^m \sum_j^n
$$

In [107]:
# menggunakan numpy

A=np.array([[1,2],[3,4]])
B=np.array([[1,1],[2,2]])
C=np.dot(A,B) # dapat ditulis menggunakan operator @--> C=A@B
D=np.inner(A,np.transpose(B))
E=A*B
print(f'Dot product A.B=\n{C}')
print(f'Menggunakan inner product A.B=\n{D}')
print(f'perkalian elemen A*B=\n{E}')

Dot product A.B=
[[ 5  5]
 [11 11]]
Menggunakan inner product A.B=
[[ 5  5]
 [11 11]]
perkalian elemen A*B=
[[1 2]
 [6 8]]


array([[ 5,  5],
       [11, 11]])

In [79]:
a=np.array([[1,2,3,4],[1,2,3,4]])
a.shape

(2, 4)

In [86]:
# mendefinisikan fungsi

def gfDot(A,B):
    m=B.shape[0]
    n=A.shape[1]
    C=np.zeros((m,n))
    
    for i in range(m):
        for j in range(n):
            #loop untuk C_{ij}
            for ci in range(m): # untuk tiap baris
                C[i,j]+=A[i,ci]*B[ci,j]
    return C
    
C=gfDot(A,B)
print(f'dot product:\n{C}')


dot product:
[[ 5.  5.]
 [11. 11.]]


# Determinan matriks
### Matriks $2\times 2$

Untuk matriks $2\times 2$,

$$
{\bf A} = \left[
\begin{matrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{matrix}
\right]
$$

Determinan $|{\bf A}|$ dihitung dengan,
$$
|{\bf A}| = a_{11}a_{22} - a_{12}a_{21}
$$

Contoh:
$$
\begin{aligned}
{\bf A} &= \left[
\begin{matrix}
1 & 2 \\
3 & 4  
\end{matrix}
\right] \\ &\\
\text{det}({\bf A}) &= |{\bf A}| = (1\times 4)-(2\times 3)
\end{aligned}
$$ 



In [90]:
# Program mencari determinan
# ingat! Python menggunakan indeks array mulai dari 0

def det2(A):
    if A.shape[0] != 2 or A.shape[1] != 2:
        return float('nan')
    return A[0,0]*A[1,1] - A[0,1]*A[1,0]

dd=det2(np.array([[1,2],[3,4]]))
print(f'determinan {dd}')

determinan -2


### Matriks $3\times 3$

$$
{\bf A} = 
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{matrix}
\right]
$$

Determinan dihitung $\rightarrow$ **Metode Sarrus** \
Menggunakan perkalian elemen melintang (_criss-cross_):

$$
\begin{aligned}
|{\bf A}| = &(a_{11}a_{22}a_{33}+a_{12}a_{23}a_{31}+a_{13}a_{21}a_{32}) - \\
&(a_{13}a_{22}a_{31}+a_{11}a_{23}a_{32}+a_{12}a_{21}a_{33})
\end{aligned}
$$

Contoh:
$$
{\bf B} = \left[
\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{matrix}
\right]
$$ 

$$
\begin{aligned}
|{\bf B}| &= \left|\begin{array}{ccc|cc}  
1 & 2 & 3  &  1 & 2\\
4 & 5 & 6 & 4 & 5 \\
7 & 8 & 9  & 7 & 8 \\
\end{array}\right| \\ &\\
&=((1.5.9)+(2.6.7)+(3.4.8))- \color{red}{((3.5.7)+(1.6.8)+(2.4.9))} \\
&=0
\end{aligned}
$$

**perhatikan**: determinan matriks yang bernilai nol!

In [129]:
def det3(A):
    if A.shape[0] != 3 or A.shape[1] != 3:
        return float('nan')
    
    return (
        A[0,0]*A[1,1]*A[2,2] + 
        A[0,1]*A[1,2]*A[2,0] +
        A[0,2]*A[1,0]*A[2,1] -
        A[0,2]*A[1,1]*A[2,0] -
        A[0,0]*A[1,2]*A[2,1] -
        A[0,1]*A[1,0]*A[2,2]
    )

ddd=det3(
    np.array([[1,2,3],
              [4,7,6],
              [7,8,9]]))

print(f'determinan: {ddd}')
mrn=np.random.rand(3,3)
drn=det3(mrn)
print(f'\nmatriks\n{mrn}')
print(f'determinan: {drn}')

determinan: -24

matriks
[[0.50406021 0.11256504 0.20954861]
 [0.40185044 0.05265381 0.41651321]
 [0.95247292 0.19905742 0.88543308]]
determinan: -0.007434149195210078


## Aturan Cramer

Determinant dapat dihitung menggunakan aturan Cramer sehingga determinan dapat dicari dengan hanya memperhitungkan determinan dari bagian matriks yang lebih kecil. Bagian matriks yang lebih kecil didefinisikan sebagai berikut,

${\bf A}_{ij} \rightarrow$ matriks dengan menghapus baris ke-$i$ dan kolom ke-$j$. Matriks ini memiliki orde lebih kecil satu dari matriks utama.

Contoh untuk,

$$
{\bf A} = \left[ 
\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{matrix}
\right]
$$

maka untuk mendapatkan ${\bf A}_{21}$,

$$
\left[ 
\begin{matrix}
\color{red}{1} & 2 & 3\\
\colorbox{green}{\color{red}{\bf 4}} & \color{red}{5} & \color{red}{6}\\
\color{red}{7} & 8 & 9
\end{matrix}
\right] \rightarrow
{\bf A}_{21} = \left[
\begin{matrix}
2 &3 \\ 8 &9
\end{matrix}
\right]
$$

Elemen yang diwarnai merah adalah elemen-elemen yang dihilangkan. Elemen dengan latar hijau disebut dengan _elemen minor_ ($a_{ij}$), dan determinan dari matriks bagian  ${\bf A}_{21}$ disebut _minor_ dari matriks $M_{ij}$. _Kofaktor_ matriks didapatkan dengan jalan mengalikan _minor_ dengan tanda posisi pada matriks asal,
$$
C_{ij} = (-1)^{(i+j)}\times M_{ij}
$$
Dengan cara ini dapat dibangun matriks kofaktor dari ${\bf A}$,

$$
{\bf C}_A = \left[
\begin{matrix}
C_{11} & C_{12} & C_{13} \\
C_{21} & C_{22} & C_{23} \\
C_{31} & C_{32} & C_{33}
\end{matrix}
\right]
$$

Determinan dapat dihitung melalui matriks ${\bf C}_A$ sebagai berikut,
$$
\begin{aligned}
|{\bf A}| 
&= \sum_{j} a_{1j}\times C_{1j} \\
&= \sum_{j} a_{2j}\times C_{2j} \\
&= \sum_{j} a_{3j}\times C_{3j} \\
\end{aligned}
$$

Sehingga dapat dipilih baris mana saja untuk mendapatkan $|{\bf A}|$.

Untuk matriks $n\times n$,

$$
{\bf C}_A = \left[
\begin{matrix}
C_{11} & C_{12} & ... & C_{1n} \\
C_{21} & C_{22} & ... & C_{2n} \\
\vdots & \vdots & \vdots & \vdots \\
C_{n1} & C_{n2} & ... & C_{nn}
\end{matrix}
\right]
$$

Perhitungan kofaktor dilakukan secara iteratif atau rekursif hingga orde bagian matriks $2\times 2$.

### Matriks Adjoin

Adjoin dari matriks didefisisikan sebagai transpos dari matriks kofaktor,

$$
\text{adj}({\bf A}) = {\bf C}_A^T
$$

Matriks ini digunakan untuk mencari invers (balikan) dari sebuah matriks, mengikuti persamaan,

$$
{\bf A}^{-1} = \frac{\text{adj}({\bf A})}{|{\bf A}|}
$$


In [141]:
# Mencari minor matriks

def mat_minor(A, i, j):
    aa=np.delete(A,i,axis=0)
    aa=np.delete(aa,j,axis=1)
    return aa

# Determinan 2x2
def det2(A):
    if A.shape[0] != 2 or A.shape[1] != 2:
        return float('nan')
    return A[0,0]*A[1,1] - A[0,1]*A[1,0]    

# Determinan nxn
def cdet(A):
    A=np.array(A)
    if len(A) == 1: return A[0][0]
    if len(A) == 2: return det2(A)
    dd = 0
    for j in range(len(A)):
        sign = (-1) ** j
        minor = mat_minor(A, 0, j)
        dd += sign * A[0][j] * cdet(minor)
    return dd

# contoh:
matA = [
    [1, 2, 3],
    [4, 7, 6],
    [7, 8, 9]
]

matB = np.random.rand(5,5)
dd = cdet(matB)
print(matB)
print()
print(f"determinan: {dd}")

[[0.0357031  0.6243741  0.68795538 0.39327476 0.7387116 ]
 [0.77072549 0.57519917 0.87024049 0.82910141 0.93967973]
 [0.1315978  0.73585251 0.63821991 0.13150506 0.35186182]
 [0.33018676 0.08735843 0.58819204 0.20137946 0.74125213]
 [0.03456363 0.7055527  0.05493616 0.33963789 0.89511715]]

determinan: -0.08810879691122607


## Menuliskan sistem persamaan Linear dalam matriks

### Persamaan linear

Persamaan linear dapat diartikan sebagai hubungan antar variabel dalam sebuah model matematis. Sebuah sistem persamaan linier terdiri dari banyak persamaan dengan jumlah variabel yang bersesuaian dengan jumlah persamaan. Variabel-variabel dinotasikan dengan simbol $x_i$ ini saling berkaitan satu sama lain. $i

$$
\begin{aligned}
a_{11}x_1+a_{12}x_2+a_{13}x_3+...+a_{1n}x_n&=y_1 \\
a_{21}x_1+a_{22}x_2+a_{23}x_3+...+a_{2n}x_n&=y_2 \\
a_{31}x_1+a_{32}x_2+a_{33}x_3+...+a_{3n}x_n&=y_3 \\
& \vdots \\
a_{n1}x_1+a_{n2}x_2+a_{n3}x_3+...+a_{nn}x_n&=y_n
\end{aligned}
$$